### Register
POST http://localhost:8080/api/auth/register
Content-Type: application/json

{
  "nom": "Othmane",
  "email": "othmane@test.com",
  "password": "123456",
  "role": "ROLE_ADMIN"
}

### Login
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "email": "othmane@test.com",
  "password": "123456"
}


### Register an employee
POST http://localhost:8080/api/auth/register
Content-Type: application/json

{
  "nom": "Hiba Test",
  "email": "hiba@test.com",
  "password": "secret123",
  "role": "ROLE_EMPLOYE"
}

### Login as employee
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
"email": "hiba@test.com",
"password": "secret123"
}


### Create a leave request
POST http://localhost:8080/api/conge
Content-Type: application/json
Authorization: Bearer TOKEN
{
  "dateDebut": "2026-06-20",
  "dateFin": "2026-06-25",
  "type": "annuel"
}

### Get my leave requests
GET http://localhost:8080/api/conge/me
Authorization: Bearer TOKEN
### Register an admin
POST http://localhost:8080/api/auth/register
Content-Type: application/json

{
  "nom": "Admin Test",
  "email": "admin@test.com",
  "password": "admin123",
  "role": "ROLE_ADMIN"
}


### Login as admin
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "email": "admin@test.com",
  "password": "admin123"
}


### Get stats for employee
GET http://localhost:8080/api/stats?userId=6a306c42fb9042c9987cd5f8&month=6&year=2026
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJoaWJhQHRlc3QuY29tIiwicm9sZSI6IlJPTEVfRU1QTE9ZRSIsImlhdCI6MTc4MTU2NDY2OCwiZXhwIjoxNzgxNjUxMDY4fQ.uNhO48vs2yrzx9CojDQmSJhZtl97Kz3nwffWvMbx56j8W_2gDTw9dmusfO1D4tMZ

### Get anomalies for employee
GET http://localhost:8080/api/stats/anomalies?userId=6a306c42fb9042c9987cd5f8&month=6&year=2026
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJoaWJhQHRlc3QuY29tIiwicm9sZSI6IlJPTEVfRU1QTE9ZRSIsImlhdCI6MTc4MTU2NDY2OCwiZXhwIjoxNzgxNjUxMDY4fQ.uNhO48vs2yrzx9CojDQmSJhZtl97Kz3nwffWvMbx56j8W_2gDTw9dmusfO1D4tMZ

### Get all employees stats (admin)
GET http://localhost:8080/api/stats/all?month=6&year=2026
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJhZG1pbkB0ZXN0LmNvbSIsInJvbGUiOiJST0xFX0FETUlOIiwiaWF0IjoxNzgxNTY0OTQxLCJleHAiOjE3ODE2NTEzNDF9.TfmRzDjV5VtZM9x4Gnr_Oo3Aki5FvL0pD2nOsqDNoSI1i1qP4dSjTWXDFSnsjli9


### Security check - employee tries to get all stats (should fail)
GET http://localhost:8080/api/stats/all?month=6&year=2026
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJoaWJhQHRlc3QuY29tIiwicm9sZSI6IlJPTEVfRU1QTE9ZRSIsImlhdCI6MTc4MTU2NDY2OCwiZXhwIjoxNzgxNjUxMDY4fQ.uNhO48vs2yrzx9CojDQmSJhZtl97Kz3nwffWvMbx56j8W_2gDTw9dmusfO1D4tMZ





